### ISSUE TITLE
A question about equation 2

### ISSUE THREAD

**Issue by peter943** [wy1iu/NSL#2]
Wonderful job！I studied your paper these days, which is very enlightening to me.

I have a question about equation 2 in your paper. If the matrix M is  block-diagonal, the result of equation 2 is equivalent to summing the output of the each channel. This operator can be replaced by averaging pooling or something else. I do not know whether this understand is right? Thank you for your kind help.

**Comment by wy1iu** [comment]
Hi, thanks for your interest in our work.

"If the matrix M is block-diagonal, the result of equation 2 is equivalent to summing the output of the each channel."
-- When the matrix M is block-diagonal, you can view the equation 2 as multiple inner products in each channel, and then sum them up. In general, your understanding is right. In this case, it is equivalent to summing up the output of each channel, but the computation in each channel is like a small bilinear inner prodcut.

"This operator can be replaced by averaging pooling or something else."
-- If you can have the ouput from each channel (which is a small bilinear inner product like the form "WMX"), of course you can then use something like an average pooling to sum them up (or aggregate them). But this will restrict to the case that M is a block-diagonal matrix. The bilinear form could be more general than that.

**Comment by peter943** [comment]
@wy1iu Thanks a lot. I was wondering whether it is possible that I could ask you a more question.

In your paper, you say: In order to further stablize the training, we learn the residual of an identity similarity matrix instead of directly learning the entire similarity matrix.

 I am not quite sure how to achieve it. Maybe I should initialize a random weight matrix W and identity matrix I and add them together which is similar to ResNet. Just change WX to (W+I)X and the rest of module stays the same. I do not know whether this understand is right? 

I'm using the zero matrix now to initialize W (W+I is an identity matrix corresponding to the traditional Conv), I do not know if that's appropriate. Thanks again for your kind help.

**Comment by wy1iu** [comment]
Your understanding is basically right. But there are some details that you may need to pay attention to. To help you better implement the method, we will release our implementation in 1-2 days. Thanks

**Comment by lzzcd001** [comment]
We have released the code for image recognition. Hope that clarifies things for you.

**Comment by peter943** [comment]
@lzzcd001 @wy1iu Thank you very much. It helps me a lot.
